In [1]:
# Import libraries

# Pandas
import pandas as pd
from collections import Counter

import matplotlib.pyplot as plt
import numpy as np


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.metrics import confusion_matrix


from sklearn.linear_model import LogisticRegression

from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import accuracy_score
from imblearn.metrics import classification_report_imbalanced
from sklearn.metrics import classification_report
from imblearn.ensemble import EasyEnsembleClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import plot_precision_recall_curve
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

from sklearn.svm import SVC
import sklearn as skl
import tensorflow as tf

In [2]:
file = '../clean_ml_data_0625.csv'
clean_df = pd.read_csv(file)

In [ ]:
# clean_df = clean_df.sample(100000)

In [3]:
clean_df.head()

gender  pneumonia  pregnant  diabetes  copd  asthma  immunosup  \
0       0          0         0         0     0       0          0   
1       0          0         0         0     0       0          0   
2       1          0         0         0     0       0          0   
3       0          0         0         0     0       0          0   
4       0          0         0         0     0       0          0   

   hypertension  cardiovascular  obesity  renal_chronic  tobacco  \
0             0               0        0              0        0   
1             0               0        0              0        0   
2             1               0        0              0        0   
3             0               0        0              0        0   
4             0               0        1              0        0   

   closed_contact  another_complication  death  intubation  ICU  new_age  
0               0                     0      0           0    0        3  
1               0                     0      0           0    0        2  
2               1                     0      0           0    0        4  
3               1                     0      0           0    0        3  
4               0                     0      0           0    0        3

In [4]:
Counter(clean_df.death)

Counter({0: 1271359, 1: 146332})

In [5]:
y= clean_df['death']
X = clean_df.drop(columns = ['ICU','intubation','death'])

In [6]:
X

gender  pneumonia  pregnant  diabetes  copd  asthma  immunosup  \
0             0          0         0         0     0       0          0   
1             0          0         0         0     0       0          0   
2             1          0         0         0     0       0          0   
3             0          0         0         0     0       0          0   
4             0          0         0         0     0       0          0   
...         ...        ...       ...       ...   ...     ...        ...   
1417686       0          1         0         0     0       0          0   
1417687       1          0         0         0     0       0          0   
1417688       1          1         0         1     0       0          0   
1417689       0          0         0         1     0       0          0   
1417690       1          0         0         0     0       0          0   

         hypertension  cardiovascular  obesity  renal_chronic  tobacco  \
0                   0               0        0              0        0   
1                   0               0        0              0        0   
2                   1               0        0              0        0   
3                   0               0        0              0        0   
4                   0               0        1              0        0   
...               ...             ...      ...            ...      ...   
1417686             0               0        0              0        0   
1417687             0               0        0              0        0   
1417688             1               0        0              0        0   
1417689             0               0        0              0        0   
1417690             1               0        0              0        0   

         closed_contact  another_complication  new_age  
0                     0                     0        3  
1                     0                     0        2  
2                     1                     0        4  
3                     1                     0        3  
4                     0                     0        3  
...                 ...                   ...      ...  
1417686               0                     0        5  
1417687               0                     0        3  
1417688               1                     0        5  
1417689               1                     0        3  
1417690               1                     0        4  

[1417691 rows x 15 columns]

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state =42, stratify=y)

In [15]:
# Creating StandardScaler instance
scaler = StandardScaler()
# Fitting standard scaler
X_scaler = scaler.fit(X_train)

# Scaling data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [17]:
# # Resample the training data with SMOTE 8min
# from imblearn.over_sampling import SMOTE
# X_resampled_s, y_resampled_s = SMOTE(random_state=1,
# sampling_strategy='auto').fit_resample(X_train_scaled,y_train)
# Counter(y_resampled_s)

Counter({0: 953519, 1: 953519})

In [8]:
from imblearn.ensemble import BalancedRandomForestClassifier 
# 8:22 - 8:24
brfc100 = BalancedRandomForestClassifier(n_estimators=100, random_state=1)
brfc100.fit(X_train,y_train)
brfc100_pred = brfc100.predict(X_test)
print(balanced_accuracy_score(y_test, brfc100_pred))
print(confusion_matrix(y_test, brfc100_pred))
print(classification_report_imbalanced(y_test, brfc100_pred))

0.8658812319773153
[[269569  48271]
 [  4257  32326]]
                   pre       rec       spe        f1       geo       iba       sup

          0       0.98      0.85      0.88      0.91      0.87      0.75    317840
          1       0.40      0.88      0.85      0.55      0.87      0.75     36583

avg / total       0.92      0.85      0.88      0.87      0.87      0.75    354423



In [9]:
from imblearn.ensemble import BalancedRandomForestClassifier 
# 12:58 - 1:00
brfc75 = BalancedRandomForestClassifier(n_estimators=75, random_state=1)
brfc75.fit(X_train,y_train)
brfc75_pred = brfc75.predict(X_test)
print(balanced_accuracy_score(y_test, brfc75_pred))
print(confusion_matrix(y_test, brfc75_pred))
print(classification_report_imbalanced(y_test, brfc75_pred))

0.8659059113576684
[[269576  48264]
 [  4256  32327]]
                   pre       rec       spe        f1       geo       iba       sup

          0       0.98      0.85      0.88      0.91      0.87      0.75    317840
          1       0.40      0.88      0.85      0.55      0.87      0.75     36583

avg / total       0.92      0.85      0.88      0.87      0.87      0.75    354423



In [10]:
from imblearn.ensemble import BalancedRandomForestClassifier 
# 1:01 - 1:02
brfc50 = BalancedRandomForestClassifier(n_estimators=50, random_state=1)
brfc50.fit(X_train,y_train)
brfc50_pred = brfc50.predict(X_test)
print(balanced_accuracy_score(y_test, brfc50_pred))
print(confusion_matrix(y_test, brfc50_pred))
print(classification_report_imbalanced(y_test, brfc50_pred))

0.8659337196455761
[[269724  48116]
 [  4271  32312]]
                   pre       rec       spe        f1       geo       iba       sup

          0       0.98      0.85      0.88      0.91      0.87      0.75    317840
          1       0.40      0.88      0.85      0.55      0.87      0.75     36583

avg / total       0.92      0.85      0.88      0.87      0.87      0.75    354423



In [11]:
from imblearn.ensemble import BalancedRandomForestClassifier 
# 1:01 - 1:02
brfc25 = BalancedRandomForestClassifier(n_estimators=25, random_state=1)
brfc25.fit(X_train,y_train)
brfc25_pred = brfc25.predict(X_test)
print(balanced_accuracy_score(y_test, brfc25_pred))
print(confusion_matrix(y_test, brfc25_pred))
print(classification_report_imbalanced(y_test, brfc25_pred))

0.8657744283952076
[[269727  48113]
 [  4283  32300]]
                   pre       rec       spe        f1       geo       iba       sup

          0       0.98      0.85      0.88      0.91      0.87      0.75    317840
          1       0.40      0.88      0.85      0.55      0.87      0.75     36583

avg / total       0.92      0.85      0.88      0.87      0.87      0.75    354423



In [12]:
# Save as zipped pickle file 1:11 - 1:17
import gzip, pickle, pickletools 
filepath = "balanced_random_forest50.pkl"
with gzip.open(filepath, "wb") as f:
    pickled = pickle.dumps(brfc50)
    optimized_pickle = pickletools.optimize(pickled)
    f.write(optimized_pickle)

In [13]:
with gzip.open(filepath, 'rb') as f:
    p = pickle.Unpickler(f)
    brf_pkl = p.load()
    predict = brf_pkl.predict(X_test)
    result = brf_pkl.score(X_test, y_test)

In [14]:
result

0.8521907438287019